services:
  db:
    image: postgres:16
    container_name: mei-finance-db
    restart: always
    environment:
      POSTGRES_DB: douradoCtrl
      POSTGRES_USER: douradoCtrl
      POSTGRES_PASSWORD: douradoCtrl
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   container_name: mei-finance-adminer
  #   restart: always
  #   ports:
  #     - 9090:8080
  #   depends_on:
  #     - db

